### ISSUE TITLE
[Install]: Spaces do not seem to be allowed in the initial user's password

### ISSUE THREAD

**Issue by jcowgar** [itsManjeet/rlxos#124]
On a fresh system install, after reboot and in the Initial Setup. If you use a space in the user password, the Initial Setup will fail. The window changes to:

```
Installation Failed

sh: line 1: secure: command not found
Exit with 127
```

On the same machine, rebooting again, the system enters the Initial Setup phase again. If you enter a password with no spaces, setup is a success.

**Comment by itsManjeet** [comment]
fixed with [8b36ba827ae90274eca4b42784cfab942201f927](https://github.com/itsManjeet/rlxos/commit/8b36ba827ae90274eca4b42784cfab942201f927#diff-14f0f30c777095b9818e93c04e804a30179fdcd27fffe22ce5586054d1459d90)
