### ISSUE TITLE
Website problem

### ISSUE THREAD

**Issue by gzmiller** [itsManjeet/rlxos#2]
Problem with `https://rlxos.dev/`: title is always `Home - rlxos`, even in download page.

**Comment by itsManjeet** [comment]
OK, thanks for the bug report, 
I used the sample template for every page that's why it happens
😅 I am very bad at website development and lazy too.

**Comment by jayesh-ahire** [comment]
if you want i can help you with website development and maintaining it

**Comment by itsManjeet** [comment]
@jayesh-ahire I apologize for a very late reply to your comment, i might didn't seen your comment on this issue. It will be very helpful. Currently website is using django as backend, if are still motivated to help than you can join our discord group to get more close discussion on this topic.
