### ISSUE TITLE
"No such file or directory" when updating

### ISSUE THREAD

**Issue by Ndashka-Dev** [itsManjeet/rlxos#20]
When I try to update the system, by typing in `bolt update my system`, it returns

```
upgrading system
error: loading sysroot: openat(boot/loader/version): No such file or directory
failed to get system updates
hello
```

That is a freshly installed system, from an ISO downloaded yesterday. I am using rlxos workstation, Linux kernel version 6.0.7 with EFI support. The laptop is Lenovo X380 Yoga. Restarting the system did not help.

**Comment by itsManjeet** [comment]
#17 can you provide your `/etc/fstab` entry, possibly your EFI partition is not mounted at /boot,
default /etc/fstab is using LABEL=EFI, for now you can try UUID= to mount EFI partition.

**Comment by itsManjeet** [comment]
fstab is supported but not needed, core filesystem mount is handled by systemd using partition GUID, so system boot perfectly fine, 
Error occur because systemd mounting efi partition at /efi ostree expect it at /boot

**Comment by itsManjeet** [comment]
For now you can manually create entires for boot partition

**Comment by itsManjeet** [comment]
FIXED in experimental release, feel free to reopen

**Comment by Ndashka-Dev** [comment]
I tried the experimental release, the error has been fixed. Thank you!

**Comment by Ndashka-Dev** [comment]
Are there any estimates, when this will be merged into the Desktop/Workstation releases?
