### ISSUE TITLE
Please add microcodes in grub

### ISSUE THREAD

**Issue by DEVHELP24** [itsManjeet/rlxos#234]
Please add the latest cpu microcodes in grub2

**Comment by itsManjeet** [comment]
Hey,Thanks for bug report. 
Microcodes are provided within the initramfs.img, you can verify that using `lsinitrd /boot/ostree/rlxos-<hash>/initramfs-<version>.img` at `kernel/x86/microcode/AuthenticAMD.bin` for AMD CPU, however the require microcode for Intel CPU i.e. GenuineIntel.bin is missing. I'll take a lot into it.
