### ISSUE TITLE
Still no working fonts... 

### ISSUE THREAD

**Issue by DEVHELP24** [itsManjeet/rlxos#253]
should I remove local /home/.config__??

(AFTEr 2.0.)

**Comment by itsManjeet** [comment]
Can you elaborate your issue?

**Comment by DEVHELP24** [comment]
The writen fonts in he desktop are just non visible like this

[][][][][][][][]

**Comment by DEVHELP24** [comment]
https://github.com/itsManjeet/rlxos/issues/254
