### ISSUE TITLE
Switching to OpenRC

### ISSUE THREAD

**Issue by DEVHELP24** [itsManjeet/rlxos#288]
No systemd... please!!!!!

**Comment by itsManjeet** [comment]
Hi, This issue is already in discussion @ #266 you can follow up on the same issue to present your views

**Comment by itsManjeet** [comment]
openrc is not is the consideration, it holds nearly the same level of complexity with less features

**Comment by DEVHELP24** [comment]
OpenRC need just an /> systemd unit/service/target converter....
