### ISSUE TITLE
Implement Root Partition Verification using dm-verity on Boot

### ISSUE THREAD

**Issue by TheHolyTachanka** [itsManjeet/rlxos#29]
I'm suggesting the integration of dm-verity as a mechanism to verify the integrity of the root partition during the boot phase. dm-verity provides a robust and proven solution to detect any unauthorized modifications that might have occurred while the system was powered off.

**Comment by itsManjeet** [comment]
dm-verity is planned for future release with A/B update mechanism , You can follow up the [rolling](https://github.com/itsManjeet/rlxos/tree/rolling) branch. Need some missing components like update mechanism and boot loader manager.

**Comment by itsManjeet** [comment]
#31
