### ISSUE TITLE
[Bug] Build fails at "Reinstalling PKGUPD"

### ISSUE THREAD

**Issue by ACertainTopfi** [itsManjeet/rlxos#5]
**Describe the bug**
Using build.sh, as provided by the official rlxOS repository, leads to a build failure fairly early on at the "reinstalling pkgupd" section of the script. Executing the same command (sudo pkgupd in pkgupd --force --skip-depends) outside the script does not yield an error.

**To Reproduce**
1. Install newest build of rlxOS in GNOME Boxes
2. Install both git and docker via pkgupd
3. git clone https://github.com/itsManjeet/rlxos.git
4. Start docker daemon by running "sudo dockerd"
5. Execute "sudo ./build.sh -p desktop"
6. After docker has pulled ~300mb, script tries to execute "pkgupd in pkgupd --force --skip-depends"
7. "Error! Failed to reinstall pkgupd"

**Expected behavior**
Script should build rlxOS. Executing "sudo pkgupd in pkgupd --force --skip-depends" outside the script does work as expected.

**Additional information**
I am currently trying to learn as much as I can about the current state of immutable Linux distributions, including the different strategies projects use to build bootable images (Lorax, Buildstream, etc.), which leads to me occasionally stumbling across an issue when it comes to reproducing official builds. Hope, that this isn't just a case of me being incapable of following the build instructions. Additionally, I would love if there was some more in-depth information on how PKGUPD handles the immutable nature of rlxOS, compared to for example rpm-ostree on Silverblue. I will dive into the source code of PKGUPD myself, so I can get a better understanding how it works, though a technical explanation by the creator would of course be very helpful.

**Comment by itsManjeet** [comment]
ok got it
The issues arises because of the temporary pretasks that i added while creating the PKGUPD package manager. So whats is doing is that its searching for a preexisting pkgupd package archive which is missing in the pkgs/ directory
Thanks for reporting the issue,

**Comment by itsManjeet** [comment]
6274ed822807ee0eece3166a9ff9d249685b8fa8 
@ACertainTopfi  please checkout the latest commit which fixed the issue, And also feel free to reopen this issue if you still face any such issue
