### ISSUE TITLE
Docs on making your own images?

### ISSUE THREAD

**Issue by ilovethensa** [itsManjeet/rlxos#50]
Would be helpful to write a couple of paragraphs on how to build a custom image and stuff

**Comment by itsManjeet** [comment]
uh, as of now I have no enough manpower and time for that, but if you interested in creating one you can either use the `experimental` (BuildStream) and `1.x` (Ignite) based source code. Output as https://rlxos.dev/downloads

`Experimental` branch uses [Build Stream 2.0](https://buildstream.build/) Documentation available https://docs.buildstream.build/2.1/index.html

Install prerequisites: [ostree, buildstream 2 and depends, golang, cargo, bsdtar, lzip] and some python modules for plugins.

To build installer image execute the command,  `bst build installer/image.bst`

`1.x` is the new branch with our homegrown tool `Ignite` in replacement of `BuildStream`

Prerequisites: golang, bsdtar and docker.

To build execute following command,

```
# To build ./build/ignite
make

# To build Installer image
./build/ignite build boards/amd64/image.yml

# To output Image
./build/ignite checkout boards/amd64/image.yml here/
`

To reuse already build cache from rlxos repository
`./build/ignite pull <component-id>`
