### ISSUE TITLE
Erro install rlxos in boot

### ISSUE THREAD

**Issue by marcio3aa** [itsManjeet/rlxos#6]
msg error on boot: cant find rootfs LABEL=RLXOS, stop boot!

**Comment by itsManjeet** [comment]
Hey, weird as this issue is fixed after 2107 releases
please let me know the ISO version you are using and/or are you using any unusual system configurations

**Comment by marcio3aa** [comment]
Version 2207, Using the Website Recommendations, using the DD, I also tried with Balena Etcher and the same error!

**Comment by itsManjeet** [comment]
Can you provide me the `lsmod` output from any of your working linux system As i am using only standard drivers builtins in linux kernel for faster booting. but i guess this is not a good idea :-p
https://github.com/itsManjeet/rlxos/tree/master/files/initramfs this contains the targeted code

just to make myself sure, can you please add `debug` in grub menu (press c while grub boot menu and add "debug" after linux /boot/..... stuff) and check if its going through `loading modules` stage

**Comment by marcio3aa** [comment]
I took a picture, even putting debug on the root of the same! 
https://i.imgur.com/kvTwBqh.jpg

**Comment by Marcio2AA** [comment]
itsManjeet, I managed to install Rlxos, apparently the front panel USB does not allow the installation, I only managed to use the motherboard rear ports, using the installer and gparted with GPT I had another difficulty, putting only EFI in Label does not work, the installer complains that did not find the EFI, just found putting EFI in Label and Name of the partition.

**Comment by itsManjeet** [comment]
I am not really sure about the issue for front and back panel port,
for the EFI complaints by installer, the code https://github.com/itsManjeet/installer/blob/main/installer/verification.go#L108 explain the thing,
Installer uses the output of `lsblk` to list system partitions.
Please verify the output by `lsblk -o label,path` and check if you see any partition with label "EFI"
