### ISSUE TITLE
Update README.md and docs on website about swupd

### ISSUE THREAD

**Issue by nixrunner** [itsManjeet/rlxos#71]
![doc](https://github.com/itsManjeet/rlxos/assets/26308212/b1d1bb3c-b2de-45f6-a79e-033e455af6fa)

Update the documentation accordingly. Swupd is not an "in-house" developed package manager. It is developed by Intel and Clear Linux Project. Reference: https://github.com/clearlinux/swupd-client/blob/master/docs/swupd.1.rst

The wording on the docs should be changed to avoid future problems.

**Comment by nixrunner** [comment]
You might consider a name change. This will cause a lot of confusion.

**Comment by itsManjeet** [comment]
FIXED with 076e448
