### ISSUE TITLE
Improve the Installation Process & GUI

### ISSUE THREAD

**Issue by manikandancode** [itsManjeet/rlxos#88]
1. Implement a simple straightforward installation process for beginners without opening the Gparted as default. (like New Ubuntu Desktop Installer and Calamares). It will help first-time Linux users.

2. Include editing partition using Gparted as an advanced user option.

3. Disable the Next Button (or remove that button).

During the installation process (That is after clicking the Apply button. Plz check the image.). if we click the Next button, it also shows a success message without any installation status check. 
![image](https://github.com/itsManjeet/rlxos/assets/46480489/a896aa28-1ced-4a4d-9583-6b37463d1182)

4. After the reboot, directly display the user account creation screen and avoid showing the same "Welcome to rlxOS" and setup screen. Alternatively, change the screen text to something like "rlxOS installed successfully, and now you are prompted to provide user account details."
This screen and the initial OS installation setup screens appear identical, creating the impression that the installation process is starting again and that the previous attempt failed.

Thanks

**Comment by itsManjeet** [comment]
Yeh, Initial Setup need improvement, Even some user though that as live environment 😅,
Add entry in the board for tracking

**Comment by itsManjeet** [comment]
FIXED with 161c0d70884bd6453c1bcaffde886e15009fb194
